#                                                                                                      
#,-.----.                                                                                              
#\    /  \                                             ,---,                        ___      ,---,     
#|   :    \   ,--,                                    '  .' \                     ,--.'|_  ,--.' |     
#|   |  .\ :,--.'|                                   /  ;    '.             ,--,  |  | :,' |  |  :     
#.   :  |: ||  |,     ,----._,.  ,----._,.          :  :       \          ,'_ /|  :  : ' : :  :  :     
#|   |   \ :`--'_    /   /  ' / /   /  ' /     .--, :  |   /\   \    .--. |  | :.;__,'  /  :  |  |,--. 
#|   : .   /,' ,'|  |   :     ||   :     |   /_ ./| |  :  ' ;.   : ,'_ /| :  . ||  |   |   |  :  '   | 
#;   | |`-' '  | |  |   | .\  .|   | .\  ., ' , ' : |  |  ;/  \   \|  ' | |  . .:__,'| :   |  |   /' : 
#|   | ;    |  | :  .   ; ';  |.   ; ';  /___/ \: | '  :  | \  \ ,'|  | ' |  | |  '  : |__ '  :  | | | 
#:   ' |    '  : |__'   .   . |'   .   . |.  \  ' | |  |  '  '--'  :  | : ;  ; |  |  | '.'||  |  ' | : 
#:   : :    |  | '.'|`---`-'| | `---`-'| | \  ;   : |  :  :        '  :  `--'   \ ;  :    ;|  :  :_:,' 
#|   | :    ;  :    ;.'__/\_: | .'__/\_: |  \  \  ; |  | ,'        :  ,      .-./ |  ,   / |  | ,'     
#`---'.|    |  ,   / |   :    : |   :    :   :  \  \`--''           `--`----'      ---`-'  `--''       
#  `---`     ---`-'   \   \  /   \   \  /     \  ' ;                                                   
#                      `--`-'     `--`-'       `--`                                                    

#If enabled, interaction with blocks will be allowed when not authenticated
allow-block-interact: false
#If enabled, dropping items will be allowed when not authenticated
allow-item-drop: false
#If enabled, picking up items will be allowed when not authenticated
allow-item-pickup: false
#If enabled, picking up arrows will be allowed when not authenticated
allow-arrow-pickup: false
#If enabled, hitting others will be allowed when not authenticated
allow-damage-others: false
#If enabled, placing blocks will be allowed when not authenticated
allow-block-place: false
#If enabled, breaking blocks will be allowed when not authenticated
allow-block-break: false
#If enabled, xp changes will be allowed when not authenticated
allow-xp-change: false
#If enabled, effect time will still go when not authenticated
allow-effect-tick: false
#If enabled, movement will be will be allowed when not authenticated
allow-movement: false
#If enabled, eating will be allowed when not authenticated
allow-eating: false
#If enabled, commands (other than /login, /register, /forgetpassword, /sendpin) will be allowed when not authenticated
allow-commands: false
#If enabled, hunger will not be stopped when not authenticated
allow-hunger: false
#If enabled, damage will not be stopped when not authenticated
allow-damage: false
#If enabled, healing will not be stopped when not authenticated
allow-heal: false
#If enabled, you can login without /login
chat-login: true
#If enabled, you will be authenticated automatically if your uuid matches the last uuid used.
auto-authentication: false
#Minimum password length
minimum-password-length: 6
#Kick players after certain time
timeout: true
#Seconds before kicked if not authenticated
timeout-time: 60
#Tries before kicked, set <= 0 to prevent from client hack
tries: 5
#If enabled, a popup will be shown when not authenticated
popup: true
#If enabled, a tip will be shown when not authenticated
tip: true
#If enabled, a boss bar will be shown when not authenticated
boss-bar: true
#Seconds til next message
seconds-til-next-message: 5
#Passwords you want blocked
blocked-passwords: ["password", "123456", "abcdef", "qwerty"]
#If enabled, players will be invisible til authentication
invisible: true
#If enabled, players will be blind til authentication
blindness: true
#If enabled, players can see chat messages when not authenticted
see-messages: false
#If enabled, players joining when another player has their username is kicked
single-session: true
#If enabled, players with logged in with xbox are automatically registered/logged in. (ClearSky only!)
xbox-bypass: false
#Disable authentication for the username Steve (default username in MCPE)
steve-bypass: true
#Capes will be given for registered players
cape-for-registration: true
#Hide items til logged in
hide-items: true
#Send progress reports every certain number of players registered
progress-reports: true
#Email to send progress report to
progress-report-email: youremail@gmail.com
#Number of players before send progress report
progress-report-number: 100
#What progress report says
progress-report: "Your server ({ip}:{port}) has reached {players} players! Your {players}th player is {player}."
#If enabled, there will be a special key that resets every 5 mins and after every use to allow access to any account.
key: true
#Username of owner, for key
owner: TheOwnerLovesPig
#If on, will prevent join message til logged in
hold-join-message: true
#If on, there will be a seperate join message for new players
join-message-for-new-players: true
#Join message for new players
new-player: "&eWelcome {player} to the server!"
#Hides all players til logged in
hide-players: true
#Hides true health til logged in
hide-health: true
#Hides true hunger til logged in
hide-hunger: true
#Hides true xp til logged in
hide-xp: true
#Hides effects til logged in
hide-effects: true
#Return to spawn when logged in
return-to-spawn: false
#If on, players will be set to adventure mode til logged in
adventure-mode: true
#Database (sqlite3, mysql)
database: sqlite3
#MySQL login
mysql:
  host: host
  user: user
  name: name
  password: password
  port: 3306
#Version
version: v2.0.1
#Auto update config
config-update: true

#Emails
send-email-on-resetpassword: true
send-email-on-changepassword: true

#Messages

#Join
join-message: "&6This server requires an account."

#Login
login: "&6Please login by typing in /login <password>\n&6Forgot your password? Use /forgotpassword <pin> <newpassword>"
login-popup: "&6Please login."
login-tip: "&6Please login."
login-boss-bar: "&6Please login."
authentication-success: "&aYou have been authenticated."
authentication-success-uuid: "&aYou have been authenticated by UUID."
authentication-success-xbox: "&aYou have been authenticated by Xbox Live."
attempted-logins: "&6There have been {attempts} attempts to login into your account."
already-authenticated: "&cYou have already logged in."
incorrect-password: "&cIncorrect password. {tries} left."
not-registered: "&cYou are not registered."
too-many-tries: "&cToo Many Tries to Login"
timeout-message: "&cLogin Timeout"

#Register
register: "&6Please register by typing in /register <password> <confirm password> [email]"
register-popup: "&6Please register."
register-tip: "&6Please register."
register-boss-bar: "&6Please register."
register-success: "&aYou have been registered. Your pin is {pin}."
register-success-xbox: "&aYou have been registered by Xbox Live. Your pin is {pin}. Your password is {password}. Change it with /changepassword."
already-registered: "&cYou are already registered."
password-too-short: "&cPassword is too short."
password-blocked: "&cPassword is blocked."
password-username: "&cUsername can't be password."
password-not-match: "&cYour password is not the same."
confirm-password: "&aPlease confirm your password."

#Preregister
preregister-success: "&aAccount has been registered."
registered-two: "&cPlayer already registered."

#Change password
change-password-success: "&aYour password has been changed. Your new pin is {pin}."

#Forget password
forgot-password-success: "&aYour password has been changed. Your new pin is {pin}."
incorrect-pin: "&cIncorrect pin."

#Reset password
password-reset-success: "&aPlayer's password has been reset."
not-registered-two: "&cPlayer not registered."

#Email
email: "&6Now type in your email. Type 'none' to skip."
email-set: "&aEmail has been set."
email-change-success:  "&aEmail changed."
email-success: "&aEmail has been sent."
email-fail: "&cEmail could not send."
invalid-email: "&cInvalid email."
no-email: "&cThere is no email connected to this account."

email-subject-sendpin: "PiggyAuth Pin Request"
email-sendpin: "Your pin is {pin}. If you did not request to send your pin, please ignore this."
email-subject-attemptedlogin: "PiggyAuth Attempted Login Notice"
email-attemptedlogin: "Someone has attempted to login to your account. If that was not you, please do /sendpin. You will recieve a 4 digit pin number to reset your password."
email-subject-changedpassword: "PiggyAuth Password Changed Notice"
email-changedpassword: "Your password was changed. If that was not you, please do /sendpin. You will recieve a 4 digit pin number to reset your password."
email-subject-passwordreset: "PiggyAuth Password Reset Notice"
email-passwordreset: "Your password was reset by a staff member. Please go on and register to claim your account."

#Pin
pin: "&aYour pin: {pin}"

#Key
key-expired: "&cYour key is expired."

#General
dont-say-password: "&cDo not say your password."
